### ISSUE TITLE
Implementation of model based on Class diagram

### ISSUE THREAD

**Issue by DusanBucan** [DusanBucan/UKS#2]

**Comment by MicaTravica** [comment]
![alt slika](http://www.plantuml.com/plantuml/png/VL6nJiCm4Dtz5LR6IgvWPwZKHWYfD55JviXDRZ3OSMLVn03yExQnhX3aJZwzz-wzq_F6etGu6ytasQEJ0_91I-yvV_7WTe1IQSzPmXB4FvYOmpj90qnS0lnktSY-ikG4qaH9f0bidNs50PVmizBWqKuG25IeWzy8Vd3gWifEJAJJ-b5Y96P84otlvHaqBsmELbj7qgqrHc7KPWUOPiDFqhzr6810D6rzO4-7lZqsZyUwwzXsttJrZXoYjfH5buch8uQfz_YJzhl8XqyXKet_qDHSGdbrjrwlAYv4deYYXUf-eSWD_nKjRU9zDnMvAPRTGap5LyHU_wiaI074BStJZvLMSp955AudlcGVLILk0zCu6_qD)

http://www.plantuml.com/plantuml/png/VL6nJiCm4Dtz5LR6IgvWPwZKHWYfD55JviXDRZ3OSMLVn03yExQnhX3aJZwzz-wzq_F6etGu6ytasQEJ0_91I-yvV_7WTe1IQSzPmXB4FvYOmpj90qnS0lnktSY-ikG4qaH9f0bidNs50PVmizBWqKuG25IeWzy8Vd3gWifEJAJJ-b5Y96P84otlvHaqBsmELbj7qgqrHc7KPWUOPiDFqhzr6810D6rzO4-7lZqsZyUwwzXsttJrZXoYjfH5buch8uQfz_YJzhl8XqyXKet_qDHSGdbrjrwlAYv4deYYXUf-eSWD_nKjRU9zDnMvAPRTGap5LyHU_wiaI074BStJZvLMSp955AudlcGVLILk0zCu6_qD

**Comment by MicaTravica** [comment]
![alt text](http://www.plantuml.com/plantuml/png/VL9DJm8n4BttLpHx95cYL-C10nj3ea0Mr2CfkvDGRRUaCuq7zR_RRjcgHRXDtiTxquy9ah3aj69YXsH5GxnH0f7p9mGx0n9I8VzWfMnPwJpK2GsiF7Z9kx4U0-qL7f0DEGliYqLxS0TRbAEBle7TWD297S2LDQ_GKD-LKOzI0PBfu4YI9ELZMy36oWD9qx6oFyYs5HG81t4Q0Xx43XI_u6wCCZR9fqPhIOC-Pku5xhq0EgVvHk3RcZpi9TEwkjjKCpPVR5VryhwkrkimrzNpl7fXi-MYIh71Tcc9j7RvKq1-sYBrg3b01wsF-_qsjvzboGDmYePhxb5UN8t7eu9xB4w9IeRYEbCSd-EFA8-99xhX0b5s05bWmKUdIaTx4rVD5V7IsR4tPzCNE2S81OdB5uqV8BTcpQdY_tDUucDyK9tZ9j2rJgjl)
http://www.plantuml.com/plantuml/uml/VL9DJm8n4BttLpHx95cYL-C10nj3ea0Mr2CfkvDGRRUaCuq7zR_RRjcgHRXDtiTxquy9ah3aj69YXsH5GxnH0f7p9mGx0n9I8VzWfMnPwJpK2GsiF7Z9kx4U0-qL7f0DEGliYqLxS0TRbAEBle7TWD297S2LDQ_GKD-LKOzI0PBfu4YI9ELZMy36oWD9qx6oFyYs5HG81t4Q0Xx43XI_u6wCCZR9fqPhIOC-Pku5xhq0EgVvHk3RcZpi9TEwkjjKCpPVR5VryhwkrkimrzNpl7fXi-MYIh71Tcc9j7RvKq1-sYBrg3b01wsF-_qsjvzboGDmYePhxb5UN8t7eu9xB4w9IeRYEbCSd-EFA8-99xhX0b5s05bWmKUdIaTx4rVD5V7IsR4tPzCNE2S81OdB5uqV8BTcpQdY_tDUucDyK9tZ9j2rJgjl

**Comment by MicaTravica** [comment]
![alt text](http://www.plantuml.com/plantuml/png/TL9BRzim3BxpLmWv1cYnNOSTEhH6KM1hYoHRZuPYCp4RFGoHMjSz_ljapLQM5BxO7_WzI8cwOj51eZNG6Csir5V6e7u1jT1gmVhPayCMq6eoiAF0KZjj4VR1nvwXJvuN7reWhdKZz1q7b39tkmnYZo6cH30wEOtVayimXnpTWwHEKalCv1tdGfRy6UUw9UdYTXokxxnusETItGU_8uDr30Pys6j7FxMa4B1ejocMoJK8V7Zj4UI5H8Pfo1sm9LVYDwZjlrEVT7qC_XaRUKjyIHrPlCDC2Ob1Q96RG7tkdM-rRhMaSiGCYlUptg9HCyR66n-AzDfRIt9S1t2qLeVN4qkdkKiETD6gZUR3Mf8oUQvNrQTDTGDtz_NZwk5sLQtN0rvLt-wg9xXvkA-cFjasDr6P_vWj2TKyGF0zEcnBq1CTQ0p27vBAUMCVVrzS_BT1E4ArU7zvkLoen2_U3IXl0eRFL2ZKj8qv-xncePP5aO_wGMbcSeZpEZK9etG-pEl67S7O-9mj3sL6aDlCSVcbG8cOocVcuLEeCs_UHqfDn3B_f_kvGjT6Q_u2)
http://www.plantuml.com/plantuml/uml/TL9BRzim3BxpLmWv1cYnNOSTEhH6KM1hYoHRZuPYCp4RFGoHMjSz_ljapLQM5BxO7_WzI8cwOj51eZNG6Csir5V6e7u1jT1gmVhPayCMq6eoiAF0KZjj4VR1nvwXJvuN7reWhdKZz1q7b39tkmnYZo6cH30wEOtVayimXnpTWwHEKalCv1tdGfRy6UUw9UdYTXokxxnusETItGU_8uDr30Pys6j7FxMa4B1ejocMoJK8V7Zj4UI5H8Pfo1sm9LVYDwZjlrEVT7qC_XaRUKjyIHrPlCDC2Ob1Q96RG7tkdM-rRhMaSiGCYlUptg9HCyR66n-AzDfRIt9S1t2qLeVN4qkdkKiETD6gZUR3Mf8oUQvNrQTDTGDtz_NZwk5sLQtN0rvLt-wg9xXvkA-cFjasDr6P_vWj2TKyGF0zEcnBq1CTQ0p27vBAUMCVVrzS_BT1E4ArU7zvkLoen2_U3IXl0eRFL2ZKj8qv-xncePP5aO_wGMbcSeZpEZK9etG-pEl67S7O-9mj3sL6aDlCSVcbG8cOocVcuLEeCs_UHqfDn3B_f_kvGjT6Q_u2
